### ISSUE TITLE
please warn that this project requires tdlib < 1.6.5

### ISSUE THREAD

**Issue by hacktivista** [ars3niy/tdlib-purple#120]
It took me one day to compile tdlib on a SBC only to discover that the version I compiled is incompatible with this project.

**Comment by BenWiederhake** [comment]
Where would you put this warning? It's already there in `CMakeLists.txt`. If you find a good place, just make a PR.

**Comment by c0dev0id** [comment]
I'm currently looking into packaging tdlib-purple for OpenBSD. We have tdlib 1.7.7 already, which is required for the telegram cli client "tg". Now, before I start bundling tdlib 1.6.5 into the tdlib-purple port, I want to ask if tdlib-purple wants to support newer tdlibs in mid-term (aka someone is working on it) or if it's going to be stuck on 1.6.5 for the foreseeable future.

**Comment by BenWiederhake** [comment]
Want: Yes
someone is working on it: No
going to be stuck on 1.6.5 for the foreseeable future: Yes, probably … unless I can convince you to port it? :D

This might be a helpful starting point: https://github.com/ars3niy/tdlib-purple/pull/98
In particular, I hope it's really only a silly issue regarding either chat names, or some kind of ID that I misunderstood. The bug is probably in the diff, even, but I'm just too stupid.

**Comment by c0dev0id** [comment]
Hi Ben, thanks for the prompt response. This looks like more than wiping out a few incompatibilities. Thanks for the pointer to the diff.

**Comment by ars3niy** [comment]
The thing with tdlib is that even minor versions can be incompatible in major ways. It's not really meant to be a system-wide shared library.

**Comment by mckaygerhard** [comment]
guys now take in consideration https://github.com/telegramdesktop/tdesktop/issues/17330 telegram changes api now.. RPCError 406: UPDATE_APP_TO_LOGIN (caused by SignInRequest)
