### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BenWiederhake** [ars3niy/tdlib-purple#2]
In order to work on your code, I need a license (= legal permission) from you. Just like you have permission to use telegram-purple due to its [license](https://github.com/majn/telegram-purple/blob/master/COPYING).

This website is a nice overview: https://choosealicense.com/
Furthermore, if you choose GPL that would make things the easiest, because then we can re-use the relevant parts of tgp's code and files without any trouble.

Giving out a license could be as simple as putting in a `COPYING` or `LICENSE` file.

**Comment by EionRobb** [comment]
You'll need to pick a license that's compatible with libpurple, i.e. GPL2 or newer

**Comment by EionRobb** [comment]
Oh, TDLib links against OpenSSL which is a GPL no-no.  You'll need to rewrite tdlib to not use openssl (or use one of the openssl compatible headers for a GPL-compatible library) before you can legally distribute this plugin

**Comment by ars3niy** [comment]
I really don't care about what people would do with own code, it's just a glue between tdlib and libpurple which for me is too insignificant to care about. But as you said, it has to be GPL. Also, this is technically a derivative of telegram-purple because that's where I borrowed skeleton for protocol plug-in from, so one more reason why it has to be GPL.

However, as far as distributing this plug-in in source form is concerned, openssl license doesn't matter does it? Because what if you do somehow build tdlib using gnutls-openssl or something – it has nothing to do with this code, right? So we can just say it's GPL and continue on our merry way until time comes to make binary packages... right? Right?

**Comment by ars3niy** [comment]
Actually, in situations where OpenSSL license even matters at all, such as making debian packages, one can just build tdlib using OpenSSL 3.0 branch which has Apache 2.0 license, which they say is compatible with GPLv3. So, problem solved?

**Comment by BenWiederhake** [comment]
> However, as far as distributing this plug-in in source form is concerned, openssl license doesn't matter does it?

You're right. The OpenSSL stuff only applies to binary distributions.

> So we can just say it's GPL and continue on our merry way until time comes to make binary packages

Precisely. In order to GPL it, just copy this file https://github.com/licenses/license-templates/blob/master/templates/gpl3.txt as the file `LICENSE` into your repo, and I (and other people) can legally use it :)

> using OpenSSL 3.0 branch which has Apache 2.0 license

Honestly, I have no idea. Either way, it won't be a problem for you. @EionRobb probably knows more.

**Comment by ars3niy** [comment]
Yep did something like that in my last commit. Just don't add any new contacts with it :)
