### ISSUE TITLE
Support formatting, and don't sent quotes as &quot; etc.

### ISSUE THREAD

**Issue by ars3niy** [ars3niy/tdlib-purple#24]

**Comment by BenWiederhake** [comment]
Just as a heads-up: pidgin/purple likes to send weird stuff like [`<SPAN style="direction:rtl;text-align:right;">…</SPAN>`](https://github.com/majn/telegram-purple/commit/550dc485c093fd7aad7513cdcf8b0c581a3a93b9) instead of just letting the frontend figure out how it wants to display things.

What I'm trying to say is: Don't be like libtgl and attempt to parse HTML, because it'll fail and cause problem down the road. Also, failing gracefully is a good idea, by sending "weird stuff" rather than nothing. Humans tend to be pretty fault-tolerant.

Libtgl just prints "Send message failed" to the debug console, swallows the message as if it had never happened, and doesn't even tell the user what happened! Arrgh I dislike this kind of behavior.

**Comment by ars3niy** [comment]
Let's just purple_unescape_html, that one should be safe
