### ISSUE TITLE
Can't lock file ... Spectrum2 use

### ISSUE THREAD

**Issue by thundergreen** [ars3niy/tdlib-purple#53]
Dear all, we have two major problems using this library with spectrum2

1. Registration asks for password which does  not work with telegram
2. mmy entering just a rando password by registering the transport we get this error:

```
Authentication error: code 400 (Can't lock file "/var/lib/spectrum2/telegram.emevth.no-ip.biz/tdlib/+3378xxxxxxxxx/td.binlog", because it is already in use by current program)
```

any idea what's going wrong here?

This is the manager:

[Spectrum2](https://github.com/SpectrumIM/spectrum2)

**Comment by ars3niy** [comment]
> Registration asks for password which does not work with telegram

By this, do you mean that the jabber transport asks for both login and password when you connect to it? If so then it is a minor problem with spectrum (or XMPP for all I know): this protocol plugin has OPT_PROTO_NO_PASSWORD flag set since there is no traditional concept of password in telegram. For example, when adding account in pidgin with this plugin, there is no input field for password, and spectrum should behave likewise (provided it's possible with XMPP).

As for the error, it looks as if the telegram account is activated twice. Can you please do one of the following:
* Restart spectrum with PURPLE_VERBOSE_DEBUG environment variable set AND stdout and stderr redirected to some file, reproduce the problem, and show me the log file and the sequence of steps to reproduce. If you never got as far as entering the one-time password for first login then the only private information in the log for you to sanitize should be the phone number.
* Or else, give me a crash course on how to reproduce this on my localhost.

**Comment by vitalyster** [comment]
This is [the root issue](https://github.com/tdlib/td/issues/915) - transport is linked to sqlite while tdlib linked to sqlcipher, tdlib crashed when trying to call `sqlcipher_export` but file lock is not correctly disposed on transport restart and we got "Can't lock file" message

**Comment by vitalyster** [comment]
Additional info - https://discuss.zetetic.net/t/can-sqlite-and-sqlcipher-be-used-simultaneously/3609/3

**Comment by ars3niy** [comment]
> This is [the root issue](https://github.com/tdlib/td/issues/915) - transport is linked to sqlite while tdlib linked to sqlcipher, tdlib crashed when trying to call `sqlcipher_export`

Strange, the plugin should be dlopen'ed in such a way that symbols exported from it (such as sqlite3_open which creates the sqlite function sqlcipher_export inside a few nested function calls) won't interact with symbols in the executable.

Does your libtelegram-tdlib.so link to tdlib statically (like it does in packages I'm building), or as a shared library?

By the way, "no such function: sqlcipher_export" is supposed to be an error condition, not a crash. If you do see a crash then it's a separate problem.

> tdlib crashed when trying to call `sqlcipher_export` but file lock is not correctly disposed on transport restart

But if tdlib does crash then this shouldn't be happening. It sounds more like spectrum calls PurplePluginProtocolInfo::login second time without calling PurplePluginProtocolInfo::close on the previous attempt. Can you check if this is what's happening, or send me that log so I can check myself?

**Comment by ars3niy** [comment]
Never mind, I reproduced both errors by linking pidgin against libsqlite3 (don't even need to call any of its functions). There is a connection error due to the sqlcipher_export thing, no crash, then "can't lock" error on reconnect because tdlib doesn't quite shut down properly following this (very unexpected) sqlite glitch.

The proper solution would be to add support for RTLD_DEEPBIND dlopen flag to g_module_open function in glib, then update libpurple to use that when loading plugins. As a workaround, linking spectrum statically against libsqlite3 should help.

**Comment by ars3niy** [comment]
Actually, there seems to be a way to fix it in the plugin, as long as it's statically linked against tdlib.

**Comment by ars3niy** [comment]
Please try the latest git revision. If you were using my binary packages before then you can install tdlib from the same repository.

**Comment by vitalyster** [comment]
Yes, it works now, but there are new issues, please check my PR
