### ISSUE TITLE
Order is broken under load

### ISSUE THREAD

**Issue by BenWiederhake** [ars3niy/tdlib-purple#58]
Steps to reproduce: Be in a chat (e.g. tdlib-purple discussion), be offline (i.e. tdlib-purple is *not* running), have several people send "intensive" things (dunno what exactly that means, but it occurred with stickers and photos for me), and then go online again.

Expected behavior: It might take a moment to catch up, and I don't care about the intermediate states. But eventually, when it's done, everything should be in the right order.

Actual behavior: It is not in the correct order. This seems to be due to the asynchronous nature of tdlib. My best guess is that "heavy" things like photos or stickers have an extra, asynchronous processing step in them, and those messages are only inserted into the chat once they are finished processing. This appears to also affect replies; dunno why.

Screenshot for illustration:

![out-of-order](https://user-images.githubusercontent.com/2690845/86583511-b403f280-bf83-11ea-8313-5c10650294c1.png)

**Comment by ars3niy** [comment]
Showing everything in-order would mean postponing messages that arrive while files (images in this case) are downloaded and stickers are converted, until after those operations are completed. Retrieving quoted message for a reply is also asynchronous, if much quicker, that's why replies are affected.

I was hesitant to do that because what if connection goes down while downloading a file, what to do with all those pending messages then? My current solution is sort of what facebook plugin does, but better (facebook displays empty message where I write "Downloading image").

**Comment by ars3niy** [comment]
Come think of it, it could make sense to at least postpone messages that came while downloading quoted message for a reply, because the reply itself is silently postponed already (and then displayed anyway should it take longer than 1 second to download quoted message).

**Comment by BenWiederhake** [comment]
You're right that "Downloading image" is better than an unexplained empty message :)

The connection going down shouldn't be a permanent thing, or even happen very often. I don't know how tdlib works, but a naive approach would be to display messages in the right order as far as possible without leaving any gaps, and if the connection goes down just abort there, and discard everything from the future. When reconnecting, tdlib-purple would need to redownload those messages again. If they appeared out of order before, then they're probably "lightweight" messages like text-only or only small images.

This feels a lot like #15: In both cases, "some previous history" should be loaded.

**Comment by ars3niy** [comment]
First step towards displaying things in order: https://github.com/ars3niy/tdlib-purple/commit/fe90927a8b48e4782d29ff31e1f79cbed01e3fd5

**Comment by ars3niy** [comment]
Latest git snapshot should mostly display things in order now. I'll make a new version after testing it some more.

Sources of out-of-order display are:
- replies for which cited message takes more than one second to retrieve (unlikely);
- downloads that take longer than one second, or which are asked about due to being above auto-download limit;
- all non-photo, non-sticker downloads with bitlbee and pidgin;
- conversion of animated stickers (message about "Converting sticker" will be displayed in order, the sticker itself not).

I may just change animated stickers to use white background instead of transparent one, which speeds up conversion significantly, and then display them in order as well.

**Comment by ars3niy** [comment]
Bitlbee and spectrum, not bitlbee and pidgin.

**Comment by ars3niy** [comment]
I did do that animated sticker speed-up in the latest git snapshot (though not converting them in-order just yet).

**Comment by ars3niy** [comment]
Animated stickers are now also converted in-order, and the whole thing is included in new release.
