### ISSUE TITLE
Enhancement: Print own version and commit in debug log

### ISSUE THREAD

**Issue by BenWiederhake** [ars3niy/tdlib-purple#60]
This might make it easier to check whether a user is experiencing a bug because they haven't updated yet, or is experiencing a bug because the fix doesn't work properly.

(Ran into this because I don't recall which version is currently installed, so I have to rebuild/reinstall before I can reproduce the bug.)

**Comment by BenWiederhake** [comment]
Thankfully I found this line in the log, otherwise I would have gotten a lot of headaches:

`Not loading /usr/lib/purple-2/libtelegram-tdlib.so. Another plugin with the same name (/home/user/.purple/plugins/libtelegram-tdlib.so) has already been loaded.`

Exactly this type of thing could be prevented by printing the version and commit.

**Comment by ars3niy** [comment]
> Exactly this type of thing could be prevented by printing the version and commit.

I don't think commit information is really needed because if I make any kind of change, it means I've reproduced a problem in a test case and verified that the change fixes it, meaning that I've fixed _at least something_ and can as well make a new version at that point. Should the fix be only partial, creating the need for another new version in quick succession, so be it.

One case where I recently deviated from this, by not making new version after making a fix, was interaction with spectrum developers (but then if anyone can get their plugin paths right, it's those guys).

**Comment by BenWiederhake** [comment]
Hmm. On the one hand: That's an excellent approach to this. tdlib-purple declares many more versions than telegram-purple, and that helps a lot. On the other hand: This converges to some kind of "every commit is a new version" paradigm, and there's already a way to do that automatedly: git commit hashes :P 

So if you think you don't wanna do this: Fine with me, then you can close it.

If you think you *do* want the commit in the debug log, I can look into how to do that with cmake (shouldn't be too hard after all).

**Comment by ars3niy** [comment]
I'm doing new version with every bug fix because I'm building new binary packages with every bug fix, and those are tied to versions. For a small project with infrequent changes it's fine.

I've added logging of plugin version at login, should be enough.
